### ISSUE TITLE
Should diff always be empty when Immutable.is returns true

### ISSUE THREAD

**Issue by des-des** [intelie/immutable-js-diff#10]
I am having trouble tracking down the cause of a diff. Two immutable objects return `true` when passed into Immutable.is while diff return a total replace of the object in question. Should this behaviour be possible?

**Comment by juanplopes** [comment]
Could you please provide a simple test case that reproduces the issue?

**Comment by des-des** [comment]
Trying to repo but finding it difficult. Code in question (using transit-immutable):
```js
      const payload = response.payload;

      console.log(diff(
        fromJSON(payload).get('dataValue'),
        mockState.get('dataValue')
      )); // not empty
      console.log(Immutable.is(
        fromJSON(payload).get('dataValue'),
        mockState.get('dataValue')
      )); //true :(
```
This should not happen? Will post back here if I can find simple example

**Comment by des-des** [comment]
Putting some logs into the function `primativeTypeDiff`
```js
function primitiveTypeDiff(a, b) {
  console.log(a); // Set { "dataValueId1" }
  console.log(b); // Set { "dataValueId1" }
  console.log((0, _immutable.is)(a, b)); // true
  console.log(a === b); // false
```
it seem there are some cases where you are using js equality when we need Immutable.is ?

**Comment by des-des** [comment]
Here is the test
```js
import { Set } from 'immutable';
import assert from 'assert';
import diff from 'immutable-diff';

const setDiff = diff(Set(['1']), Set(['1']));
assert.equal(setDiff.size, 0, 'there should not be a diff');
```

**Comment by des-des** [comment]
@juanplopes this seems like a bug.

**Comment by brenoferreira** [comment]
@des-des v0.4.3 was published to NPM and should fix this issue. Could you test it please?

**Comment by brenoferreira** [comment]
@pedroteixeira could you publish v0.4.3 to NPM?
